export const equipmentCategories = [
  'excavators',
  'loaders',
  'cranes',
  'dozers',
  'backhoes'
];

export const equipment = [
  {
    id: 1,
    name: "CAT 320D Excavator",
    model: "320D",
    serial: "CAT-320D-2020",
    category: "excavators",
    brand: "CAT",
    image: "/equipment/cat-320d.jpg",
    specs: {
      tonnage: "20 tons",
      enginePower: "260 hp",
      year: 2020,
      attachments: ["Hydraulic Breaker", "Ripper"],
      capacity: undefined,
      maxLift: undefined,
      boomLength: undefined,
    },
    type: "rental",
    rentalRate: {
      daily: 1200,
      weekly: 7500,
      monthly: 28000,
    },
    salePrice: undefined,
    availability: true,
    condition: "new",
    location: "Riyadh",
    maintenanceHistory: [
      { date: "2024-04-01", description: "1000-hour service completed" },
      { date: "2024-01-15", description: "500-hour service completed" },
    ],
  },
  {
    id: 2,
    name: "Komatsu PC200-10 Excavator",
    model: "PC200-10",
    serial: "KOM-PC200-2021",
    category: "excavators",
    brand: "Komatsu",
    image: "/equipment/komatsu-pc200.jpg",
    specs: {
      tonnage: "20 tons",
      enginePower: "249 hp",
      year: 2021,
      attachments: ["Hydraulic Breaker"],
      capacity: undefined,
      maxLift: undefined,
      boomLength: undefined,
    },
    type: "sale",
    rentalRate: undefined,
    salePrice: 550000,
    availability: true,
    condition: "used",
    location: "Jeddah",
    maintenanceHistory: [
      { date: "2024-03-15", description: "Full service and inspection completed" },
      { date: "2024-02-01", description: "Engine oil change" },
    ],
  },
  {
    id: 3,
    name: "Volvo EC240B Excavator",
    model: "EC240B",
    serial: "VOL-EC240-2022",
    category: "excavators",
    brand: "Volvo",
    image: "/equipment/volvo-ec240.jpg",
    specs: {
      tonnage: "24 tons",
      enginePower: "261 hp",
      year: 2022,
      attachments: ["Hydraulic Breaker", "Ripper", "Thumbs"],
      capacity: undefined,
      maxLift: undefined,
      boomLength: undefined,
    },
    type: "rental",
    rentalRate: {
      daily: 1300,
      weekly: 8500,
      monthly: 32000,
    },
    salePrice: undefined,
    availability: true,
    condition: "refurbished",
    location: "Dammam",
    maintenanceHistory: [
      { date: "2024-04-10", description: "Complete refurbishment completed" },
      { date: "2024-03-05", description: "Hydraulic system inspection" },
    ],
  },
  {
    id: 4,
    name: "CAT 988K Wheel Loader",
    model: "988K",
    serial: "CAT-988K-2023",
    category: "loaders",
    brand: "CAT",
    image: "/equipment/cat-988k.jpg",
    specs: {
      tonnage: undefined,
      enginePower: "450 hp",
      year: 2023,
      attachments: ["Bucket", "Grapple"],
      capacity: "12 tons",
      maxLift: undefined,
      boomLength: undefined,
    },
    type: "rental",
    rentalRate: {
      daily: 1500,
      weekly: 9500,
      monthly: 36000,
    },
    salePrice: undefined,
    availability: true,
    condition: "new",
    location: "Riyadh",
    maintenanceHistory: [
      { date: "2024-04-05", description: "1000-hour service completed" },
      { date: "2024-01-20", description: "500-hour service completed" },
    ],
  },
  {
    id: 5,
    name: "Liebherr LTM 1120-5.1 Mobile Crane",
    category: "cranes",
    brand: "Liebherr",
    image: "/equipment/liebherr-ltm.jpg",
    specs: {
      maxLift: "120 tons",
      boomLength: "52m",
      year: 2022,
      attachments: ["Jib", "Counterweights"],
    },
    type: "rental",
    rentalRate: {
      daily: 2500,
      weekly: 16000,
      monthly: 60000,
    },
    availability: true,
    condition: "new",
    location: "Jeddah",
    maintenanceHistory: [
      { date: "2024-04-12", description: "1000-hour service completed" },
      { date: "2024-02-25", description: "Hydraulic system inspection" },
    ],
  },
  {
    id: 6,
    name: "Hitachi ZW200-6 Wheel Loader",
    category: "loaders",
    brand: "Hitachi",
    image: "/equipment/hitachi-loader.jpg",
    specs: {
      capacity: "12 tons",
      enginePower: "260 hp",
      year: 2023,
      attachments: ["Bucket", "Grapple"],
    },
    type: "rental",
    rentalRate: {
      daily: 1900,
      weekly: 12000,
      monthly: 45000,
    },
    availability: true,
    condition: "new",
    location: "Riyadh",
    maintenanceHistory: [
      { date: "2024-04-01", description: "1000-hour service completed" },
      { date: "2024-01-15", description: "500-hour service completed" },
    ],
  }
];
